[build.environment]
  NODE_VERSION = "22"
  YARN_VERSION = "1.22.22"
  ANGULAR_PROJECT = "audio-tag-analyzer"

[build]
  # Default build command.
  command = "yarn install --frozen-lockfile && yarn ng build --configuration production"

  publish = "dist/audio-tag-analyzer"

